describe('TC01 ', () => {
    beforeEach(() => {
        cy.visit('https://e1-vhp.com/')
        cy.get('[data-cy="username-input-login"]')
        .type('qctest@qcbali03')
        cy.get('[data-cy="password-input-login"]')
        .type('vhp123')
        cy.get('[data-cy="btn-submit"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[data-cy="btn-submit"] > .q-btn__wrapper > .q-btn__content')
        .type('A3b9Z1')
        cy.get('[data-cy="btn-submit"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.wait(500)
      })
    it('TC01001. Membuka menu guest house', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-back"]')
        .contains('Guest Profile')
    })
    it('TC01002. Membuka form create Guest Profile', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('.dialog__title')
        .contains('Create Guest Profile Individual')
    })
    it('TC01003. User ingin mengisi field mandatory form create guest profile', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()
       
        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
    })
    it('TC01004. User tidak mengisi field mandatory (last name)', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()
       
        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()
        //Validasi message eror tampil
        cy.get('.q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Field is required')
    })
    it('TC01005. User tidak mengisi field mandatory (Title)', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul')
        
        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()

        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()
        //validasi eror warning
        cy.get('.q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Field is required')
    })
    it('TC01006. User tidak mengisi field mandatory (Gender)', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()

        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()
        //validasi eror warning
        cy.get('.q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Field is required')

    })
    it('TC01007. User tidak mengisi field mandatory (Country)', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()

        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(2) > .q-field__focusable-action')
        .click()

        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()
        //validasi eror warning
        cy.get('.q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Field is required')

    })
    it('TC01008. User tidak mengisi field mandatory (Nation)', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()

        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
        
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(2) > .q-field__focusable-action')
        .click()
        
        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()
        //validasi eror warning
        cy.get('.q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Field is required')

    })
    it('TC01009. User ingin mengisi field mandatory form create guest profile', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('123abdul!#')
        cy.get('[data-v-2c3f7e81=""] > .q-field > .q-field__inner > .q-field__bottom > .q-field__messages > div')
        .should('be.visible')
        .and('contain', 'Only letters, numbers, spaces, /, [, ], (, ), and & are allowed')
       
    })
    it('TC01010. User ingin mengisi semua field form create guest profile', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul lagi')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()   

        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
        cy.get('[data-cy="birthplace-input-individual"]')
        .should('be.visible')
        .click()
        .type('Bantul')

        cy.get('[data-cy="birthdate-input-individual"]')
        .invoke('val','20/05/20')
        .trigger('change')

        cy.get('[data-v-2c3f7e81=""] > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'KTP')
        .click()
        
        cy.get('.q-checkbox__bg')
        .click()

        cy.get(':nth-child(10) > [data-v-ce7e1a54=""][data-v-2c3f7e81=""] > .q-field > .q-field__inner > .q-field__control')
        .type('3424450039200')

        cy.get('.upload-id-card')
        .attachFile('id-card.jpeg', { force: true })
        .then(input => {
            const files = input[0].files
            expect(files[0].name).to.eq('id-card.jpeg')
          })

    })
    it('TC01011. User ingin melakukan submit form create guest profile', () => {
        cy.get(':nth-child(1) > .column > .img-icon')
        .click()
        cy.wait(5000)
        cy.get('[data-cy="menu-apps-button"] > .q-btn__wrapper > .q-btn__content')
        .click()
        cy.get('[href="/fr/guest-profile"]')
        .click()
        cy.get('[data-cy="btn-add-individual"] > .q-btn__wrapper > .q-btn__content > img')
        .click()
        cy.get('[data-cy="lastname-input-individual"]')
        .type('Abdul lagi')
        cy.get(':nth-child(3) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'MR').click()
       
        cy.get(':nth-child(4) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'Male')
        .click()
       
        cy.get(':nth-child(5) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
       
        cy.get(':nth-child(6) > .col-12 > .q-mt-xs > .q-field > .q-field__inner > .q-field__control > :nth-child(3) > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'IDN - INDONESIA')
        .click()
        
        cy.get('[data-cy="birthplace-input-individual"]')
        .should('be.visible')
        .click()
        .type('Bantul')

        cy.get('[data-cy="birthdate-input-individual"]')
        .invoke('val','20/05/20')
        .trigger('change')

        cy.get('[data-v-2c3f7e81=""] > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-select__dropdown-icon')
        .click()
        cy.contains('.q-item__label', 'KTP')
        .click()
        
        cy.get('.q-checkbox__bg')
        .click()

        cy.get(':nth-child(10) > [data-v-ce7e1a54=""][data-v-2c3f7e81=""] > .q-field > .q-field__inner > .q-field__control')
        .type('3424450039200')

        //upload file
        cy.get('.upload-id-card')
        .attachFile('id-card.jpeg', { force: true })
        .then(input => {
            const files = input[0].files
            expect(files[0].name).to.eq('id-card.jpeg')
          })

        cy.get('[data-cy="btn-submit-dialogFooter"] > .q-btn__wrapper')
        .click()

        cy.get('[data-autofocus="true"] > .q-btn__wrapper > .q-btn__content > .block')
        .click()

        //validasi pop up notive tampil
        cy.get('[style=""] > .q-notification__wrapper > .q-notification__content > .q-notification__message')
        .should('be.visible')
        .and('contain.text', 'Successfully save guest profile.')

        cy.wait(5000)

        cy.get('[data-cy="btn-refresh-table"] > .q-btn__wrapper > .q-btn__content > img')
        .click()

        //validasi data tersimpan
        cy.get('.q-table__container')
        .contains('td', 'Abdul lagi')
        .should('exist')
    
    })

  })